# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  catalogdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin  # Asegúrate de proporcionar una contraseña segura
      POSTGRES_DB: CatalogDb
    ports:
      - "5433:5432"
volumes:
  postgres_catalog: